version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions 
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: emulator -avd circleci-android22 -no-audio -no-window:
                   background: true
                   parallel: true
      -run:
          name: Wait for Emulator to boot
          command: circle-android wait-for-boot
      -run:
          name: Unlock the emulator screen
          command: sleep 30
                   adb shell input keyevent 82
       -run:
           name: Run tests  against the emulator
           command: ./gradlew connectedAndroidTest -PdisablePreDex
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
